channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.0.4
- pip:
  - mlflow<3,>=2.2
  - numpy==1.23.5
  - pandas==2.0.0
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - typing-extensions==4.5.0
  - xgboost==1.7.5
name: mlflow-env
